name: $3-depl
on:
push:
branches:
- main
jobs:
build:
runs-on: ubuntu-latest
steps:
- uses: actions/checkout@v2
I
- name: Configure AWS Credentials
uses: aws-actions/configure-aws -credentials@vl
with:
aws-access-key-id: $ secrets. AWS_ACCESS_KEY_ID}}
aws-secret-access-key: ${{ secrets. AWS_SECRET_ACCESS_KEY}}
aws-region: ${{ secrets. AWS_REGION }}
- name: Build React App
run: npm install && npm run build
- name: Deploy app build to $3 bucket
run: aws s3 sync ./dist/ s3://rivka-react-app
